name: 🚀 Deploy to CloudFront

on:
  push:
    branches: [main]

jobs:
  deploy_admin:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: 📦 Configurar Node.js
        uses: actions/checkout@v3

      - name: Config pnpm
        uses: pnpm/action-setup@v2

      - name: 📦 Instalación de dependencias
        run: pnpm install

      - name: 🚚 Ejecutar despliegue con SST
        run: |
          cd apps/admin
          npx sst deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          STAGE: prod
